### PR TITLE
Add waveform to player

### PR DESCRIPTION
**Pull request by cyberk**
Adds an optional waveform display above the player. To view, click the button to the left of the Loop button.

Waveform should accept clicks to jump to a point in the 

Known issue: there is a small delay in displaying the waveform because it has to load and parse the entire file from disk (it's a separate library from Howler.js).

### CODE REVIEW

**Comment by minter** [comment]
I think this looks really great - I'd consider changing the icon to something more obvious than the ^ symbol, but other than that: For the people who like this sort of thing, this is the sort of thing they'll like.

**Comment by cyberk** [comment]
The right symbol is in the FontAwesome Pro pack. I'll dig around and see if I can find a non-FA waveform icon, because I agree it's totally not the right one.

**Comment by cyberk** [comment]
@minter added better icon.

**Comment by minter** [comment]
Minor addition - added `title` element for hover.

**Pull request merged**
